name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install Deps
        run: go mod tidy
      - name: Test
        run: |
          go test ./python
          go test ./c/from_inter
          go test ./c/parse